roslaunch_package: odometry_evaluation # Ros package that contains the launch file for odometry evaluation
roslaunch_file: odometry_evaluation.launch # The roslaunch file to launch the odometry evaluation
ros_topic: /stereo_odometer # Topic to be listened to capture the visual odometry and information outputs. This must be the name of the parent odometry node.
algorithm: viso2 # The visual odometer algorithm. Can be 'viso2' or 'fovis'
gt_file: /home/plnegre/Workspace/ROS_fuerte/uib-ros/odometry_evaluation/data/gt/cirs-timefixed-run3.txt # The ground truth (gt) file to validate the odometry (used to compute the errors between gt and odometry estimation)
sample_step: 0.05 # Distance to sample equally the gt and odometry data
brute: True # True to apply brute force and try all possible combinations. False to apply an optimization function
max_iter: 3 # Maximum number of iterations in the optimization algorithm (only if brute = False)
error_to_min: 1 # 0 to minimize translation error, 1 to minimize rotation error, 2 to minimize the euclidean norm between both errors
save_output_file: output/optimization_report.txt # Output file with the optimization summary
save_output_data: output/plots/ # Output directory where optimization tables will be saved
parameters:
  - name: /stereo_odometer/nms_n # Parameter name (in ros parameter server) to be tunned.
    min_value: 1 # Minimum value for the parameter
    max_value: 1 # Maximum value for the parameter
    step: 1 # Step size (only if brute = True)