roslaunch_package: odometry_evaluation # Ros package that contains the launch file for odometry evaluation
roslaunch_file: odometry_evaluation.launch # The roslaunch file to launch the odometry evaluation
ros_topic: /stereo_odometer # Topic to be listened to capture the visual odometry output. The message type of this topic must be nav_msgs::Odometry)
algorithm: fovis # The visual odometer algorithm. Can be 'viso2' or 'fovis'
gt_file: data/gt/cirs-timefixed-run3.txt # The ground truth (gt) file to validate the odometry (used to compute the errors between gt and odometry estimation)
sample_step: 0.05 # Distance to sample equally the gt and odometry data
max_iter: 3 # Maximum number of iterations in the optimization algorithm (only if brute = False)
error_to_min: 1 # 0 to minimize translation error, 1 to minimize rotation error, 2 to minimize the euclidean norm between both errors
save_output_file: output/optimization_report.txt # Output file with the optimization summary
save_output_data: output/plots/ # Output directory where optimization tables will be saved
parameters:
  - name: /stereo_odometer/inlier_max_reprojection_error
    default: 1.5
    min_value: 0.2
    max_value: 4
    step: 0.2
  - name: /stereo_odometer/ref_frame_change_threshold
    default: 150
    min_value: 100
    max_value: 200
    step: 5
  - name: /stereo_odometer/fast-threshold-adaptive-gain
    default: 0.002
    min_value: 0.001
    max_value: 0.01
    step: 0.0005